import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const execFileMock = vi.fn();

vi.mock('node:child_process', () => ({
  execFile: execFileMock,
}));

vi.mock('../env.js', () => ({
  env: {
    GITHUB_TOKEN: 'test-github-token',
    GITHUB_ORG: 'TheDAIO',
    GITHUB_DEFAULT_REPO_PRIVATE: true,
  },
}));

const mockFetch = vi.fn();
global.fetch = mockFetch;

describe('github service', () => {
  let tempDir: string;

  beforeEach(() => {
    vi.clearAllMocks();
    tempDir = mkdtempSync(join(tmpdir(), 'daio-github-test-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('creates and pushes a product repository', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: () => Promise.resolve({
        name: 'test-product-run12345',
        html_url: 'https://github.com/TheDAIO/test-product-run12345',
        clone_url: 'https://github.com/TheDAIO/test-product-run12345.git',
        private: true,
        default_branch: 'main',
        owner: { login: 'TheDAIO' },
      }),
    });

    execFileMock.mockImplementation((_command, args, options, callback) => {
      const cb = callback as (error: Error | null, stdout: string, stderr: string) => void;
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('HEAD')) {
        cb(null, 'abc123def456\n', '');
        return;
      }
      if (Array.isArray(args) && args.includes('status') && args.includes('--porcelain')) {
        cb(null, '?? src/index.ts\n', '');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('--verify')) {
        cb(new Error('fatal: Needed a single revision'), '', 'fatal: Needed a single revision');
        return;
      }
      if (Array.isArray(args) && args.includes('remote') && args.includes('get-url')) {
        cb(new Error('No such remote'), '', 'No such remote');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('--show-toplevel')) {
        cb(new Error('not a git repo'), '', 'not a git repo');
        return;
      }
      cb(null, '', '');
    });

    const { ensureProductRepository } = await import('../services/github.js');
    const result = await ensureProductRepository({
      productName: 'Test Product',
      runId: 'run-12345',
      productDir: tempDir,
      description: 'Generated by DAIO',
    });

    expect(result.repoUrl).toBe('https://github.com/TheDAIO/test-product-run12345');
    expect(result.defaultBranch).toBe('main');
    expect(result.commitSha).toBe('abc123def456');
    expect(mockFetch).toHaveBeenCalledWith(
      'https://api.github.com/orgs/TheDAIO/repos',
      expect.objectContaining({
        method: 'POST',
      }),
    );

    const pushCall = execFileMock.mock.calls.find((call) => Array.isArray(call[1]) && call[1].includes('push'));
    expect(pushCall?.[1]).toContain('origin');
    expect(pushCall?.[1]).toContain('main');
  });

  it('retries with a suffixed repository name on conflict', async () => {
    mockFetch
      .mockResolvedValueOnce({
        ok: false,
        status: 422,
        text: () => Promise.resolve(JSON.stringify({ message: 'Repository creation failed. Name already exists on this account' })),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          name: 'test-product-run12345-2',
          html_url: 'https://github.com/TheDAIO/test-product-run12345-2',
          clone_url: 'https://github.com/TheDAIO/test-product-run12345-2.git',
          private: true,
          default_branch: 'main',
          owner: { login: 'TheDAIO' },
        }),
      });

    execFileMock.mockImplementation((_command, args, options, callback) => {
      const cb = callback as (error: Error | null, stdout: string, stderr: string) => void;
      if (Array.isArray(args) && args.includes('status') && args.includes('--porcelain')) {
        cb(null, '?? src/index.ts\n', '');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('--verify')) {
        cb(new Error('fatal: Needed a single revision'), '', 'fatal: Needed a single revision');
        return;
      }
      if (Array.isArray(args) && args.includes('remote') && args.includes('get-url')) {
        cb(new Error('No such remote'), '', 'No such remote');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('--show-toplevel')) {
        cb(new Error('not a git repo'), '', 'not a git repo');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('HEAD')) {
        cb(null, 'abc123def456\n', '');
        return;
      }
      cb(null, '', '');
    });

    const { ensureProductRepository } = await import('../services/github.js');
    const result = await ensureProductRepository({
      productName: 'Test Product',
      runId: 'run-12345',
      productDir: tempDir,
    });

    expect(result.name).toBe('test-product-run12345-2');
    expect(mockFetch).toHaveBeenCalledTimes(2);
  });

  it('throws when GitHub rejects repository creation', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: false,
      status: 403,
      statusText: 'Forbidden',
      text: () => Promise.resolve(JSON.stringify({ message: 'Resource not accessible by integration' })),
    });

    const { ensureProductRepository } = await import('../services/github.js');
    await expect(ensureProductRepository({
      productName: 'Test Product',
      runId: 'run-12345',
      productDir: tempDir,
    })).rejects.toThrow('Resource not accessible by integration');
  });

  it('initializes a nested repository instead of using the parent worktree', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: () => Promise.resolve({
        name: 'test-product-run12345',
        html_url: 'https://github.com/TheDAIO/test-product-run12345',
        clone_url: 'https://github.com/TheDAIO/test-product-run12345.git',
        private: true,
        default_branch: 'main',
        owner: { login: 'TheDAIO' },
      }),
    });

    execFileMock.mockImplementation((_command, args, options, callback) => {
      const cb = callback as (error: Error | null, stdout: string, stderr: string) => void;
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('--show-toplevel')) {
        cb(null, join(tempDir, '..'), '');
        return;
      }
      if (Array.isArray(args) && args.includes('status') && args.includes('--porcelain')) {
        cb(null, '?? src/index.ts\n', '');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('--verify')) {
        cb(new Error('fatal: Needed a single revision'), '', 'fatal: Needed a single revision');
        return;
      }
      if (Array.isArray(args) && args.includes('remote') && args.includes('get-url')) {
        cb(new Error('No such remote'), '', 'No such remote');
        return;
      }
      if (Array.isArray(args) && args.includes('rev-parse') && args.includes('HEAD')) {
        cb(null, 'abc123def456\n', '');
        return;
      }
      cb(null, '', '');
    });

    const { ensureProductRepository } = await import('../services/github.js');
    await ensureProductRepository({
      productName: 'Test Product',
      runId: 'run-12345',
      productDir: tempDir,
    });

    const initCall = execFileMock.mock.calls.find((call) => Array.isArray(call[1]) && call[1][0] === 'init');
    expect(initCall).toBeDefined();
  });
});
