-- Persist approval requests generated by HITL gates

create table if not exists public.approval_requests (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.runs(id) on delete cascade,
  stage text not null check (stage in ('research', 'ideation', 'branding', 'planning', 'development', 'deployment', 'distribution')),
  request_key text not null,
  kind text not null check (kind in ('approve-reject', 'select-one', 'rank')),
  subject text not null,
  payload jsonb not null default '{}'::jsonb,
  policy jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'resolved')),
  outcome text check (outcome in ('approved', 'retry', 'cancel')),
  decision jsonb,
  provider text,
  actor_id text,
  actor_name text,
  reason text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_approval_requests_run_id
  on public.approval_requests(run_id);

create index if not exists idx_approval_requests_run_stage_status
  on public.approval_requests(run_id, stage, status);

create unique index if not exists idx_approval_requests_pending_request
  on public.approval_requests(run_id, stage, request_key)
  where status = 'pending';

alter publication supabase_realtime add table public.approval_requests;

alter table public.approval_requests enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where policyname = 'anon_read_approval_requests'
      and tablename = 'approval_requests'
  ) then
    create policy "anon_read_approval_requests"
      on public.approval_requests
      for select
      using (true);
  end if;
end $$;
